version: '3.6'

networks:
  network:
    driver: bridge
  graylog-network:
    external: false

services:
  web:
    build: './MedicosDeRua'
    container_name: web
    ports:
      - 90:80
    networks:
      - network
    depends_on: 
      - api

  api:
    build: './Backend'
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=db
    depends_on:
      - db
    networks:
      - network
    links:
      - db
    container_name: api
    command: yarn dev
    
    ports:
      - 3333:3333

  db:
    image: bitnami/mongodb:latest
    container_name: db
    restart: always
    depends_on: 
      - graylog
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
        tag: 'Log DB'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network
    
  db_seed:
    build: './Seed'
    restart: on-failure
    networks:
      - network
    links:
      - db
    depends_on: 
      - db

  mongo:
    image: mongo:3
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog-network
    ports:
      - "27018:27017"
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - graylog-network
    
  graylog:
    image: graylog/graylog:3.1.0
    container_name: graylog
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      - TZ=America/Sao_Paulo
      - GRAYLOG_ROOT_TIMEZONE=America/Sao_Paulo
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_INDEX_PREFIX=graylog
    depends_on:
      - elasticsearch
      - mongo
    networks:
      - graylog-network
    ports:
      # GELF TCP LOG
      - 12201:12201
      # Graylog web interface and REST API
      - 9000:9000

volumes:
  mongodb_data:
    driver: local
  graylog_journal:
    driver: local
  es_data:
    driver: local
  mongo_data:
    driver: local